spring:
  datasource:
    url: jdbc:postgresql://postgres_server:5432/pokedex
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect    hibernate:      ddl-auto: create-drop
    generate-ddl: true
    show-sql: true